/*
 * TestUploadAndDownloadPicturePanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-11-04 11:40:36
 */
package com.nazca.test.ui.uploadAndDownload;

import com.nazca.test.agent.GetCompanyLicenseExamineImgAgent;
import com.nazca.test.agent.UploadPictureAgent;
import com.nazca.test.common.ScaleImagePane;
import com.nazca.test.listener.AgentListener;
import com.nazca.test.util.ResourceUtil;
import com.nazca.ui.NWaitingPanel;
import com.nazca.ui.laf.border.IconLabelBorder;
import com.nazca.ui.util.CardLayoutWrapper;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 赵洪坤 <zhaohongkun@yzhtech.com>
 */
public class TestUploadAndDownloadPicturePanel extends javax.swing.JPanel {

    private BufferedImage imgs = null;   //文件
    private UploadPictureAgent uploadPictureAgent = null;   //文件
    private CardLayoutWrapper waitCard = null;
    private GetCompanyLicenseExamineImgAgent getCompanyLicenseExamineImgAgent = null;
    private CardLayoutWrapper ImageCard = null;
    String fileName;//保存上传的图片名，为下载图片赋值
    private IconLabelBorder leftBorder = null;
    private IconLabelBorder rightBorder = null;

    /**
     * Creates new form TestUploadAndDownloadPicturePanel
     */
    public TestUploadAndDownloadPicturePanel() throws IOException {
        initComponents();
        intUi();
        initModelAndRenderer();
        initAgentAndListener();
    }

    private void initModelAndRenderer() {

    }

    private void initAgentAndListener() {
        uploadPictureAgent = new UploadPictureAgent();
        uploadPictureAgent.addListener(upLoadPictureAgentListener);
        getCompanyLicenseExamineImgAgent = new GetCompanyLicenseExamineImgAgent();
        getCompanyLicenseExamineImgAgent.addListener(queryImageAgentLis);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        uploadBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        manPicPane = new com.nazca.ui.NImagePanel();
        nWaitingPanel2 = new com.nazca.ui.NWaitingPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        nWaitingPanel1 = new com.nazca.ui.NWaitingPanel();
        scaleImagePane = new com.nazca.test.common.ScaleImagePane();
        generalMessagePanel1 = new com.nazca.test.common.GeneralMessagePanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setToolTipText("");

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 298));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        uploadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nazca/test/res/update-16.png"))); // NOI18N
        uploadBtn.setText("上传图片");
        uploadBtn.setFocusable(false);
        uploadBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(uploadBtn);

        viewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nazca/test/res/help-16.png"))); // NOI18N
        viewBtn.setText("查看图片");
        viewBtn.setFocusable(false);
        viewBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(viewBtn);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.CardLayout());

        manPicPane.setWaitingTime(10);
        jPanel3.add(manPicPane, "CONTENT");
        jPanel3.add(nWaitingPanel2, "WAIT");

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 298));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nazca/test/res/reset-16.png"))); // NOI18N
        jButton1.setText("下载图片");
        jButton1.setFocusable(false);
        jButton1.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jPanel2.add(jToolBar2, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.CardLayout());
        jPanel4.add(nWaitingPanel1, "WAIT");
        jPanel4.add(scaleImagePane, "CONTENT");

        javax.swing.GroupLayout generalMessagePanel1Layout = new javax.swing.GroupLayout(generalMessagePanel1);
        generalMessagePanel1.setLayout(generalMessagePanel1Layout);
        generalMessagePanel1Layout.setHorizontalGroup(
            generalMessagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        generalMessagePanel1Layout.setVerticalGroup(
            generalMessagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        jPanel4.add(generalMessagePanel1, "EMPTY");

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        ScaleImagePane scaleImagePane = new ScaleImagePane();
        JDialog dialog = new JDialog();
        dialog.add(scaleImagePane);
        dialog.setSize(450, 450);
        dialog.setLocationRelativeTo(null);
        dialog.setTitle("查看图片");
        dialog.setIconImage(ResourceUtil.readImage("manage-pic.png"));
        dialog.setVisible(true);
        if (imgs != null) {
            scaleImagePane.setViewImg(imgs);
        } else {
            scaleImagePane.setViewImg(ResourceUtil.readImage("manage-pic.png"));
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        //打开操作
        FileFilter filter = new FileNameExtensionFilter("图片(JPG/GIF/PNG)", "JPG", "JPEG", "GIF", "PNG");//文件过滤器               
        JFileChooser fileChooser = new JFileChooser(); //文件选择器
        fileChooser.setFileFilter(filter);
        int i = fileChooser.showOpenDialog(uploadBtn);
        if (i == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();//获得文件绝对路径
                BufferedImage img = ImageIO.read(selectedFile);
                imgs = img;
                manPicPane.removeAll();
                manPicPane.setImage(img);
                fileName = selectedFile.getName();//文件名
                InputStream is = new FileInputStream(selectedFile);
//                String attachmentDirType = fileChooser.getTypeDescription(selectedFile);
                uploadPictureAgent.setParame(fileName, is);
                uploadPictureAgent.start();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getCompanyLicenseExamineImgAgent.setImageName(fileName);
        getCompanyLicenseExamineImgAgent.start();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nazca.test.common.GeneralMessagePanel generalMessagePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private com.nazca.ui.NImagePanel manPicPane;
    private com.nazca.ui.NWaitingPanel nWaitingPanel1;
    private com.nazca.ui.NWaitingPanel nWaitingPanel2;
    private com.nazca.test.common.ScaleImagePane scaleImagePane;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
private long manPictureSeq = 0;
    AgentListener<String> upLoadPictureAgentListener
            = new AgentListener<String>() {
        @Override
        public void onStarted(long seq) {
            manPictureSeq = seq;
            nWaitingPanel2.showWaitingMode("数据加载中，请稍后...");
            nWaitingPanel2.setIndeterminate(true);
            waitCard.show(CardLayoutWrapper.WAIT);
        }

        @Override
        public void onSucceeded(String result, long seq) {
            nWaitingPanel2.setIndeterminate(false);//关闭等待面板
            if (manPictureSeq == seq) {
                waitCard.show(CardLayoutWrapper.CONTENT);
            }
        }

        @Override
        public void onFailed(String errMsg, int errCode, long seq) {
            if (seq == manPictureSeq) {
                waitCard.show(CardLayoutWrapper.WAIT);
                nWaitingPanel2.showMsgMode(errMsg, errCode, NWaitingPanel.MSG_MODE_ERROR);
            }
        }

    };
    long timeSeq = 0;
    private final AgentListener<BufferedImage> queryImageAgentLis = new AgentListener<BufferedImage>() {
        @Override
        public void onStarted(long seq) {
            timeSeq = seq;
            nWaitingPanel1.showWaitingMode("数据加载中，请稍后...");
            nWaitingPanel1.setIndeterminate(true);
            ImageCard.show(CardLayoutWrapper.WAIT);
        }

        @Override
        public void onSucceeded(BufferedImage result, long seq) {
            if (timeSeq == seq) {
                nWaitingPanel1.setIndeterminate(false);
                if (result != null) {
                    ImageCard.show(CardLayoutWrapper.CONTENT);
                    scaleImagePane.setViewImg(result);
                } else {
                    generalMessagePanel1.setText("暂无企业图片信息");
                    generalMessagePanel1.showMessage();
                    ImageCard.show(CardLayoutWrapper.EMPTY);
                }
            }
        }

        @Override
        public void onFailed(String errMsg, int errCode, long seq) {
            ImageCard.show(CardLayoutWrapper.FAIL);
            nWaitingPanel1.showMsgMode(errMsg, errCode, NWaitingPanel.MSG_MODE_ERROR);
        }
    };

    private void intUi() throws IOException {
        leftBorder = new IconLabelBorder(getClass().getResource(//左右面板标题
                "/com/nazca/test/res/32.png"), "信息列表");
        jPanel1.setBorder(leftBorder);
        rightBorder = new IconLabelBorder(getClass().getResource(
                "/com/nazca/test/res/32.png"), "详细信息");
        jPanel2.setBorder(rightBorder);
        waitCard = new CardLayoutWrapper(jPanel3);
        ImageCard = new CardLayoutWrapper(jPanel4);
        manPicPane.setImage(ResourceUtil.readImage("manage-pic.png"));
        nWaitingPanel1.setIndeterminate(false);
        ImageCard.show(CardLayoutWrapper.CONTENT);
        InputStream is = ResourceUtil.readStream("manage-pic.png");
        scaleImagePane.setViewImg(ImageIO.read(is));
    }
}
