/*
 * InitPanel.java
 * 
 * Copyright(c) 2007-2016 by Yingzhi Tech
 * All Rights Reserved
 * 
 * Created at 2016-10-14 16:24:51
 */
package com.nazca.test.ui;

import com.nazca.test.ui.testzip.ExportPanel;
import com.nazca.test.ui.uploadAndDownload.TestUploadAndDownloadPicturePanel;
import com.nazca.test.ui.testlistener.TestListenerPanel;
import com.nazca.test.ui.doubleTableCheckBox.TestSinglePanel;
import com.nazca.test.ui.doubleTableCheckBox.TestDoublePanel;
import com.nazca.test.util.FakeDataFactory;
import com.nazca.ui.laf.NazcaLAFTool;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JToggleButton;

/**
 *
 * @author 赵洪坤 <zhaohongkun@yzhtech.com>
 */
public class InitPanel extends javax.swing.JFrame {

    /**
     * Creates new form TestDoubleTable2
     */
    List<JToggleButton> list = new ArrayList();
    private TestDoublePanel studentOfCityMgmtPanel = null;
    private TestSinglePanel testSinglePanel = null;
    private TestUploadAndDownloadPicturePanel testUploadAndDownloadPicturePanel = null;
    private ExportPanel exportCarReportPane = null;
    private TestListenerPanel testListener = null;
    public InitPanel() {
        initComponents();
        initUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        contentPane = new javax.swing.JPanel();
        nNavToolBar1 = new com.nazca.ui.NNavToolBar();
        myTestOneBtn = new javax.swing.JToggleButton();
        myTestTwoBtn = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentPane.setLayout(new java.awt.BorderLayout());

        nNavToolBar1.setRollover(true);

        buttonGroup1.add(myTestOneBtn);
        myTestOneBtn.setText("单表格复选框");
        myTestOneBtn.setFocusable(false);
        myTestOneBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myTestOneBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myTestOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myTestOneBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(myTestOneBtn);

        buttonGroup1.add(myTestTwoBtn);
        myTestTwoBtn.setText("双表格复选框");
        myTestTwoBtn.setFocusable(false);
        myTestTwoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        myTestTwoBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        myTestTwoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myTestTwoBtnActionPerformed(evt);
            }
        });
        nNavToolBar1.add(myTestTwoBtn);

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setText("上传图片和下载图片");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        nNavToolBar1.add(jToggleButton1);

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("下载压缩文件");
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        nNavToolBar1.add(jToggleButton2);

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("监听者模式");
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        nNavToolBar1.add(jToggleButton3);

        contentPane.add(nNavToolBar1, java.awt.BorderLayout.NORTH);

        getContentPane().add(contentPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myTestTwoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myTestTwoBtnActionPerformed
        contentPane.removeAll();
        contentPane.add(nNavToolBar1, BorderLayout.NORTH);
        if (studentOfCityMgmtPanel == null) {
            studentOfCityMgmtPanel = new TestDoublePanel();
        }
        contentPane.add(studentOfCityMgmtPanel, BorderLayout.CENTER);
        contentPane.validate();
        contentPane.repaint();
    }//GEN-LAST:event_myTestTwoBtnActionPerformed

    private void myTestOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myTestOneBtnActionPerformed
        contentPane.removeAll();
        contentPane.add(nNavToolBar1, BorderLayout.NORTH);
        if (testSinglePanel == null) {
            testSinglePanel = new TestSinglePanel();
        }
        contentPane.add(testSinglePanel, BorderLayout.CENTER);
        contentPane.validate();
        contentPane.repaint();
    }//GEN-LAST:event_myTestOneBtnActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        contentPane.removeAll();
        contentPane.add(nNavToolBar1, BorderLayout.NORTH);
        if (testUploadAndDownloadPicturePanel == null) {
            try {
                testUploadAndDownloadPicturePanel = new TestUploadAndDownloadPicturePanel();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        contentPane.add(testUploadAndDownloadPicturePanel, BorderLayout.CENTER);
        contentPane.validate();
        contentPane.repaint();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        contentPane.removeAll();
        contentPane.add(nNavToolBar1, BorderLayout.NORTH);
        if (testUploadAndDownloadPicturePanel == null) {
            exportCarReportPane = new ExportPanel();
        }
        contentPane.add(exportCarReportPane, BorderLayout.CENTER);
        contentPane.validate();
        contentPane.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        contentPane.removeAll();
        contentPane.add(nNavToolBar1, BorderLayout.NORTH);
        if (testUploadAndDownloadPicturePanel == null) {
            testListener = new TestListenerPanel();
        }
        contentPane.add(testListener, BorderLayout.CENTER);
        contentPane.validate();
        contentPane.repaint();

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void initUI() {
        FakeDataFactory.setFake(true);
        for (Component c : nNavToolBar1.getComponents()) {
            if (c instanceof JToggleButton) {
                list.add((JToggleButton) c);
            }
        }
        //设置默认选中项
        list.get(0).doClick();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        NazcaLAFTool.applyNazcaLAF();
        JFrame jf = new InitPanel();
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.setSize(800, 600);
        jf.setLocationRelativeTo(null);
        jf.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contentPane;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton myTestOneBtn;
    private javax.swing.JToggleButton myTestTwoBtn;
    private com.nazca.ui.NNavToolBar nNavToolBar1;
    // End of variables declaration//GEN-END:variables

}
